import { WeatherLib } from '@biogrid/weather';
import { EnergySource } from './bioenergy-source';
import {
  Validatable,
  validate,
  Power,
  SunlightIntensity,
  Distance,
  CloudCoverage,
} from '@biogrid/grid-simulator';
import { SOLAR_PANEL, GRID_ITEM_NAMES } from '../config';

export class SolarPanel extends EnergySource {
  private sizeSqMtr: number;
  name: string;
  date: Date;
  private weatherLib: WeatherLib;
  /**
   * @param efficiency - default to 17.5% efficiency as solar panels are often between 15% and 20% efficiency
   */
  constructor(
    x: Distance,
    y: Distance,
    sizeSqMtr: number,
    name: string = GRID_ITEM_NAMES.SOLAR_PANEL,
    efficiency = 0.175,
    longitude = 0,
    latitude = 0,
    date: Date = new Date()
  ) {
    super(x, y, efficiency, longitude, latitude);
    if (!this.validateInputsSolarPanel(sizeSqMtr)) {
      throw new Error(
        `Cannot create a solar panel object with values of area ${sizeSqMtr}`
      );
    }
    this.sizeSqMtr = sizeSqMtr;
    this.name = name;
    this.date = date;
    this.weatherLib = new WeatherLib(date, longitude, latitude);
  }

  private validateInputsSolarPanel(area: number) {
    const validator: Validatable = {
      value: area,
      isPositive: area >= 0,
    };
    return validate(validator);
  }

  async getPowerAmount(date: Date): Promise<Power> {
    if (!this.weatherLib.isSetup()) {
      await this.weatherLib.setup();
    }
    // Solar panels do not produce energy at night
    if (!this.weatherLib.isDay(date)) {
      return 0;
    }
    const cloudCoverage = this.weatherLib.getCloudCoverage(date);
    const powerPerSqrMeter = this.cloudCoverageToKiloWattsPerSquareMeter(
      cloudCoverage
    );
    return powerPerSqrMeter * this.sizeSqMtr * this.efficiency;
  }

  supplyPower(requiredPower: Power): Power {
    // TODO implement this when you return the amount of power
    // TODO that the solar panel holds at the particular moment
    // subtract requiredPower from the current and return it, keep track of the remaining power
    return requiredPower;
  }

  /**
   * This method returns the current power that can be generated by
   * the solar panel at that given time
   */
  async getEnergyInJoules(): Promise<Power> {
    return await this.getPowerAmount(this.date);
  }

  async isEmpty() {
    return (await this.getEnergyInJoules()) === 0;
  }

  private cloudCoverageToKiloWattsPerSquareMeter(cloudCoverage: CloudCoverage) {
    // CalculationDerived from https://scool.larc.nasa.gov/lesson_plans/CloudCoverSolarRadiation.pdf
    return 990 * (1 - 0.75 * Math.pow(cloudCoverage, 3)) / 1000;
  }
}
